// Generated by https://quicktype.io

export interface CommandResponse {
  traceId: string;
  code: number;
  msg: string;
  result: CommandResult;
}

export interface CommandResult {
  traceId: string;
  code: number;
}
