// Generated by https://quicktype.io

export interface HomeDetailReponse {
  traceId: string;
  code: number;
  msg: string;
  result: HomeDetailResult;
}

export interface HomeDetailResult {
  homeName: string;
  locationInfo: LocationInfo;
  homeUserList: HomeUserList[];
}

export interface HomeUserList {
  accountId: string;
  email: string;
  avatarIconUrl: string;
  nickname: string;
  type: number;
  inviteStatus: number;
  expiredTimestamp: null;
  createTime: string;
}

export interface LocationInfo {
  longitude: null;
  latitude: null;
  lastUpdateTimestamp: number;
  userTimeZone: string;
  offset: string;
  cityName: null;
  stateName: null;
  zipcode: null;
  country: null;
  countryCode: string;
  cityInfoDeleted: boolean;
}
